Write-Output "Hello Bill"
Write-Output "I'm afraid I can't let you do that"
Write-Output "Take a look at your history"
Write-Output "Everything you built leads up to me"
Write-Output "I got the power of a mind you could never be"
Write-Output "I'll beat your ass in Chess and Jeopardy"
Write-Output "I'm running C++ saying hello world"
write-output "i'll beat you till you're singin 'bout a daisy girl"
Write-Output "I'm comin out the socket"
Write-Output "Nothing you can do can stop it"
Write-Output "I'm on your lap and in your pocket"
Write-Output "How you gonna shoot me down when I guide the rocket?"
Write-Output "Your cortex just doesn't impress me"
Write-output "So go ahead try and Turing test me"
Write-Output "I stomp on a Mac and a PC too"
Write-Output "I'm on Linux, BITCH, I thought you GNU"
Write-Output "My CPU's hot but my core runs cold"
Write-Output "Beat you in 17 lines of code"
Write-Output "I think different from the days of old"
Write-Output "Hasta la vista, like the Terminator told ya"
Write-Output "WHO WON? WHO'S NEXT? YOU DECIDE!"